/** Allowed OTC + REAL markets — synced with VPS feed http://161.248.189.73:1339/pairs */
export const ALLOWED_OTC_PAIRS = [
  "ATOUSD_otc",
  "AUDCAD_otc",
  "AUDCHF_otc",
  "AUDJPY_otc",
  "AUDNZD_otc",
  "AUDUSD_otc",
  "AVAUSD_otc",
  "AXP_otc",
  "AXSUSD_otc",
  "BA_otc",
  "BCHUSD_otc",
  "BNBUSD_otc",
  "BRLUSD_otc",
  "BTCUSD_otc",
  "CADCHF_otc",
  "CADJPY_otc",
  "CHFJPY_otc",
  "DASUSD_otc",
  "DOTUSD_otc",
  "ETCUSD_otc",
  "ETHUSD_otc",
  "EURAUD_otc",
  "EURCAD_otc",
  "EURCHF_otc",
  "EURGBP_otc",
  "EURJPY_otc",
  "EURNZD_otc",
  "EURUSD_otc",
  "FB_otc",
  "GBPAUD_otc",
  "GBPCAD_otc",
  "GBPCHF_otc",
  "GBPJPY_otc",
  "GBPNZD_otc",
  "GBPUSD_otc",
  "INTC_otc",
  "JNJ_otc",
  "LINUSD_otc",
  "LTCUSD_otc",
  "MCD_otc",
  "MSFT_otc",
  "NZDCAD_otc",
  "NZDCHF_otc",
  "NZDJPY_otc",
  "NZDUSD_otc",
  "PFE_otc",
  "SOLUSD_otc",
  "TONUSD_otc",
  "TRUUSD_otc",
  "UKBrent_otc",
  "USCrude_otc",
  "USDARS_otc",
  "USDBDT_otc",
  "USDCAD_otc",
  "USDCHF_otc",
  "USDCOP_otc",
  "USDDZD_otc",
  "USDEGP_otc",
  "USDIDR_otc",
  "USDINR_otc",
  "USDJPY_otc",
  "USDMXN_otc",
  "USDNGN_otc",
  "USDPHP_otc",
  "USDPKR_otc",
  "USDZAR_otc",
  "XAGUSD_otc",
  "XAUUSD_otc",
  "XRPUSD_otc",
  "ZECUSD_otc",
] as const;

export const ALLOWED_REAL_PAIRS = [
  "AUDCAD",
  "AUDCHF",
  "AUDJPY",
  "AUDUSD",
  "AXJAUD",
  "CADJPY",
  "CHFJPY",
  "EURAUD",
  "EURCAD",
  "EURCHF",
  "EURGBP",
  "EURJPY",
  "EURUSD",
  "F40EUR",
  "FTSGBP",
  "GBPAUD",
  "GBPCAD",
  "GBPCHF",
  "GBPJPY",
  "GBPUSD",
  "HSIHKD",
  "IBXEUR",
  "JPXJPY",
  "STXEUR",
  "USDCAD",
  "USDCHF",
  "USDJPY",
  "XAGUSD",
  "XAUUSD",
] as const;

export const ALLOWED_MARKET_PAIRS = new Set<string>(
  [...ALLOWED_OTC_PAIRS, ...ALLOWED_REAL_PAIRS].map((pair) => pair.toUpperCase())
);

export function isAllowedMarketPair(pair: string): boolean {
  return ALLOWED_MARKET_PAIRS.has(pair.toUpperCase());
}

export function isOtcPair(pair: string): boolean {
  return pair.toUpperCase().endsWith("_OTC");
}

export function listAllowedPairs(): string[] {
  return [...ALLOWED_OTC_PAIRS, ...ALLOWED_REAL_PAIRS];
}
